### ISSUE TITLE
Some Error/Exceptions are not in English

### ISSUE THREAD

**Issue by Beheadedstraw** [subzero-cli/subzero#1]
Example:
https://github.com/subzero-cli/subzero/blob/8d2e72f7ae34ca282f732bc575fcf35b0b3eb2df/infra/database.go#L126

Not a huge deal, but would suggest changing it to English like the rest just to keep things in line with the rest of the code base.

**Comment by ceelsoin** [comment]
sorry for that, i've been changing all messages to english, this is solved in latest commit

**Comment by ceelsoin** [comment]
sorry for that, i've been changing all messages to english, this is solved in latest commit
